version: '3.4'

services:
  apigateway:
    image: apigateway:dev
    container_name: ApiGateway
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ApiGateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_apigateway$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\ApiGateway:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_apigateway$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_apigateway$ \"D:/Codes/eRecruitmentOnMicroservices/ApiGateway/bin/Debug/netcoreapp3.1/ApiGateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  applying.api:
    image: applyingapi:dev
    container_name: Applying.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Applying.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_applying.api$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\Applying.API:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_applying.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_applying.api$ \"D:/Codes/eRecruitmentOnMicroservices/Applying.API/bin/Debug/netcoreapp3.1/Applying.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  identity.api:
    image: identityapi:dev
    container_name: Identity.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Identity.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_identity.api$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\Identity.API:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_identity.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_identity.api$ \"D:/Codes/eRecruitmentOnMicroservices/Identity.API/bin/Debug/netcoreapp3.1/Identity.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  identityserver.api:
    image: identityserverapi:dev
    container_name: IdentityServer.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "IdentityServer.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_identityserver.api$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\IdentityServer.API:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_identityserver.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_identityserver.api$ \"D:/Codes/eRecruitmentOnMicroservices/IdentityServer.API/bin/Debug/netcoreapp3.1/IdentityServer.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  jobs.api:
    image: jobsapi:dev
    container_name: Jobs.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Jobs.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_jobs.api$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\Jobs.API:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_jobs.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_jobs.api$ \"D:/Codes/eRecruitmentOnMicroservices/Jobs.API/bin/Debug/netcoreapp3.1/Jobs.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  webmvc:
    image: webmvc:dev
    container_name: WebMVC
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebMVC"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webmvc$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\WebMVC:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webmvc$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webmvc$ \"D:/Codes/eRecruitmentOnMicroservices/WebMVC/bin/Debug/netcoreapp3.1/WebMVC.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  webspa:
    image: webspa:dev
    container_name: WebSPA
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebSPA"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webspa$
    volumes:
      - E:\DotNetProjects\eRecruitmentOnMicroservices\WebSPA:/app
      - E:\DotNetProjects\eRecruitmentOnMicroservices:/src
      - C:\Users\ahmed\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webspa$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webspa$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
